node {
   def commit_id // tao ra commit id vi jenkins pipeline ko tu tao
   stage('Preparation') { //xac dinh buoc khoi tao
     checkout scm // dau tien check out git
     sh "git rev-parse --short HEAD > .git/commit-id"   // sau do chay lenh de commit id                     
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') { // chay install nodejs 
       sh 'npm install --only=dev' // install cac package phan dev trong package.json cua application
       sh 'npm test' // chay len npm test
     }
   }
   
   stage('docker build/push') { // step build va push len docker hub
     docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') { //login vao docker hub voi credential da nhap
       def app = docker.build("wardviaene/docker-nodejs-demo:${commit_id}", '.').push() // build docker voi ten va commit id, sau do push len dockerhub
     }
   }
}
