node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://id.docker.com/login/?next=%2Fid%2Foauth%2Fauthorize%2F%3Fclient_id%3D43f17c5f-9ba4-4f13-853d-9d0074e349a7%26next%3D%252F%253Fref%253Dlogin%26nonce%3DeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiI0M2YxN2M1Zi05YmE0LTRmMTMtODUzZC05ZDAwNzRlMzQ5YTciLCJleHAiOiIyMDIxLTA1LTEzVDA2OjUyOjM3LjQwOTQyNTk2NVoiLCJpYXQiOiIyMDIxLTA1LTEzVDA2OjQ3OjM3LjQwOTQyNjUwNVoiLCJyZnAiOiJteld3cVVHRjJmUVo3d19nZHZpQ2J3PT0iLCJ0YXJnZXRfbGlua191cmkiOiIvP3JlZj1sb2dpbiJ9.3M6DcJSI_TxFZGQ_yIuP-FsBR3HdbJ2-FFtxfoZchF8%26redirect_uri%3Dhttps%253A%252F%252Fhub.docker.com%252Fsso%252Fcallback%26response_type%3Dcode%26scope%3Dopenid%26state%3DeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiI0M2YxN2M1Zi05YmE0LTRmMTMtODUzZC05ZDAwNzRlMzQ5YTciLCJleHAiOiIyMDIxLTA1LTEzVDA2OjUyOjM3LjQwOTQyNTk2NVoiLCJpYXQiOiIyMDIxLTA1LTEzVDA2OjQ3OjM3LjQwOTQyNjUwNVoiLCJyZnAiOiJteld3cVVHRjJmUVo3d19nZHZpQ2J3PT0iLCJ0YXJnZXRfbGlua191cmkiOiIvP3JlZj1sb2dpbiJ9.3M6DcJSI_TxFZGQ_yIuP-FsBR3HdbJ2-FFtxfoZchF8','dockerhub') {
       def app = docker.build("windskyz/docker-nodejs-demo:${commit_id}", '.').push()
     }
   }
}
