node {
   def commit_id
   environment {
      registry = "windskyz/docker-nodejs-demo"
      registryCredential = 'dockerhub'
   }
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
     docker.withRegistry('',registryCredential) {
       def app = docker.build("windskyz/docker-nodejs-demo:${commit_id}", '.').push()
     }
   }
}
